<<<<<<< HEAD

spring:
=======
sspring:
>>>>>>> 5b53017 (docs : application 문서 수정)
  profiles:
    include: secret
    active: dev

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100

<<<<<<< HEAD
  datasource:
    url: jdbc:mariadb://${yourDb:localhost:3306}/planbti_dev
    username: ${yourName:sonhansol}

=======
>>>>>>> 5b53017 (docs : application 문서 수정)
  security:
    oauth2:
      client:
        registration:
          naver:
            scope:
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl:http://localhost:8080}/{action}/oauth2/code/{registrationId}'

          kakao:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl:http://localhost:8080}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST

          google:
            scope: profile
            client-name: Google
            redirect-uri: '${custom.site.baseUrl:http://localhost:8080}/{action}/oauth2/code/{registrationId}'

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  data:
    redis:
      port: ${yourRedisPort:6379}
      host: ${yourRedisIp:localhost}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 5
      timeout: 3000


decorator:
  datasource:
    p6spy:
      enable-logging: true


